kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: jenkins-node
  namespace: jenkins
  labels:
    app: jenkins-node
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: jenkins-node
        deploymentconfig: jenkins-node
    spec:
      containers:
        - name: jenkins-node
          image: registry.redhat.io/openshift4/ose-jenkins-agent-base
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
